# #Misfits Add - Brotherhood Knight-Pilot. Senior Knight tier; the chapter's vertibird aviator.
# The Brotherhood ranks by title rather than pins, so this role has no rank pin progression.

- type: job
  id: BoSKnightPilot
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false
  jobWhitelistBypassesRoleTimers: true
  weight: 69
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-knight-pilot
  overwatchCategory: OverwatchBosKnight
  description: job-description-bos-knight-pilot
  playTimeTracker: BoSKnightPilot
  requirements:
    - !type:CharacterSpeciesRequirement # BoS does not accept Ghouls or Glowing Ghouls
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement # T5 faction timelock (16h BoS)
      department: BrotherhoodOfSteel
      min: 57600 # 16 hours
  startingGear: BoSKnightPilotGear
  alwaysUseSpawner: true
  icon: "JobIconBosMKnight"
  supervisors: job-supervisors-bos-knight-pilot
  accessGroups:
  - BOSSeniorKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: VertibirdPilotPerk # #Misfits Add - pilot perk granted free with the role

- type: startingGear
  id: BoSKnightPilotGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtBOSBlack
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeatherFilled
    head: N14ClothingHeadHatCapkhighBoS
    outerClothing: MisfitsBoSKnightArmor
    hands: N14ClothingHandsGlovesCombat
    eyes: N14ClothingEyesGlassesPilot
    pocket1: BoSBrotherhoodSeniorKnightKits
    id: N14IDBrotherhoodOfSteelHolotagSeniorKnight
    ears: N14ClothingHeadsetBrotherhoodOfSteel
    belt: ClothingBeltBoSWebbing
  storage:
    back:
    - N14ClothingHeadHatBrotherhoodHelmetKnight
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSKnightPilot
